Cms/Controllers/PagesController.cs
using Cms.Models.Data;
using Cms.Models.ViewModels.Pages;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Cms.Controllers
{
    public class PagesController : Controller
    {
        // GET: Pages  - /index/{pages} || 
        //string page = "domyślnie"
        [HttpGet]
        public ActionResult Index(string page = "")
        {
            //set home page 
            if (page == "")
            {
                page = "home";
                ViewBag.IsHome = "true";
            }
            //set pageViewModel PageDTo
            PageViewModel model;
            PageDTO dTo;
            //check page exists
            using (Db db = new Db())
            {
                if (!db.Pages.Any(x => x.Slug.Equals(page)))
                {
                    return RedirectToAction("Index", new { page = "" });
                }
            }
            //get PageDTO 
            using (Db db = new Db())
            {
                dTo = db.Pages.Where(x => x.Slug == page).FirstOrDefault();
            }

            //set Page Title 
            ViewBag.PageTitle = dTo.Title;
            //set sideBar
            if (dTo.HasSidebar == true)
            {
                //get sidebar
                ViewBag.Sidebar = "1";
            }
            else
            {
                ViewBag.Sidebar = "0";
            }
            //init model PageViewModel
            model = new PageViewModel(dTo);
            //model PageViewModel
            return View(model);
        }
        //po dodaniu kodu partial, dodać  routing 
        public ActionResult PagesMenuPartial()
        {
            //declaration Page ViewModel
            List<PageViewModel> pageVMList;
            //set List
            using (Db db = new Db())
            {
                //get PageVmList
                pageVMList = db.Pages.ToArray().OrderBy(x => x.Sorting).Where(x => x.Slug != "home").Select(x => new PageViewModel(x)).ToList();

            }

            //zwracamy pageViewModelList
            return PartialView(pageVMList);

        }

        /**
         * @name Partial PagesSideBarPartial
         */
        //GET: /Pages/PagesSideBarPartial
        [HttpGet]
        public ActionResult PagesSideBarPartial()
        {
            //init pageSideBarView
            SideBarViewModel pageSideBarView;
            //get sideBar 
            using (Db db = new Db())
            {
                SideBarDTO dTO = db.SideBar.Find(1);
                //set SideBarViewModel
                pageSideBarView = new SideBarViewModel(dTO);

            }
            //return model view model
            return PartialView(pageSideBarView);

        }
        public ActionResult CaruselPartial()
        {
            //init AdvertisementList
            List<AdvertisementViewModel> advertisementViewModels = new List<AdvertisementViewModel>();
            //

            return PartialView(advertisementViewModels);
        }

    }

}

Cms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#563d7c">
    <title>@ViewBag.PageTitle</title>
    <link href="~/Template/css/main.css" rel="stylesheet">
    <link href="~/Content/jquery.fancybox.css" rel="stylesheet" />

</head>
<body>

    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-7 col-md-5 py-4">
                        @Html.Action("PagesMenuPartial", "Pages")
                    </div>
                    <div class="col-sm-5 offset-md-1 py-4">


                        <div class="col-sm-4 offset-md-1 py-4 float-right">
                            <h3 class="text-white">Strefa użytkownika</h3>
                            <ul class="list-unstyled ">

                                @if (!Request.IsAuthenticated)
                                {
                                    <li><a href="/Account/Login" class="text-white">Zaloguj</a></li>
                                }
                                <!-- Role -->
                                @if (Request.IsAuthenticated)
                                {
                                    if (User.IsInRole("default"))
                                    {
                                        @Html.Action("ProfileAccountMenuPartial", "Account")
                                    }
                                    else
                                    {
                                        <li><a href="/Admin/Dashboard/Index" class="text-white">Panel Administracyjny</a></li>
                                    }
                                    <li><a href="/Account/Logout" class="text-white">Wyloguj</a></li>

                                }
                            </ul>
                        </div>


                      
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex ">
                <div class="justify-content-start">
                    <a href="/" class="navbar-brand d-flex align-items-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" /><circle cx="12" cy="13" r="4" /></svg>
                        <strong>cmsShop</strong>
                    </a>
                </div>
                <div class="justify-content-between">
                    <form class="form-inline mt-2 mt-md-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Szukaj" aria-label="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Znajdź produkt</button>
                    </form>
                </div>
                <div class="justify-content-end">                   
                    <div class="cart">
                            @Html.Action("CartViewPartial", "Cart")                         
                        </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>
        </div>
    </header>



    <!-- Navabar Categories placeholder-->


    <main role="main" class="flex-shrink-0  bg-light">




        <!-- if Home show baner-->
        @if (ViewBag.IsHome == "true")
        {//
            <!-- show carusel with baners and images-->
        <section class="jumbotron text-center">
            <!--Partial Carusel-->
            @Html.Action("CaruselPartial", "Pages")
            

           
        </section>

        }
        <div class="container">


            <!--Partial - render body-->
            @if (ViewBag.Sidebar == "1")
            {
                <div class="row">
                    <div class="col-xs-4 col-md-2">
                        <!-- Categories Partial-->
                        @Html.Action("CategoryMenuPartial", "Shop")
                    </div>
                    <div class="col-md-10 col-xs-8">
                        <p class="lead">
                            @RenderBody()
                        </p>
                        <!-- If is home and shop is on show last add products-->
                        @if (ViewBag.IsHome == "true")
                        {//

                            @Html.Action("ListAllProductsNew", "Shop")
                          

                        }
                        <!--End Section-->

                    </div>

                </div>

            }
            else
            {<div class="row">
                    <div class="col-xs-12 col-md-12 ">
                        <p class="lead">
                            @RenderBody()
                        </p>
                    </div>
                </div>
            }

        </div>



    </main>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <!-- site Menu-->
                <a href="#">Back to top</a>
            </p>
            <div class="float-left">
                @Html.Action("PagesMenuPartial", "Pages")
            </div>

        </div>
    </footer>
    <script src="/Scripts/jquery-3.3.1.js"></script>
    <script src="/Scripts/esm/popper.js"></script>
    <script src="/Template/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="/Scripts/jquery.fancybox.js"></script>
    <script src="/Template/front.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>